version: '3.8'

services:
  chrome:
    image: selenium/node-chrome:4.1.2-20220131
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=15
    networks:
      - tg_cluster_app_network

  selenium-hub:
    image: selenium/hub:4.1.2-20220131
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    volumes:
      - ./selenium-grid.toml:/opt/selenium/config.toml
    networks:
      - tg_cluster_app_network

networks:
  tg_cluster_app_network:
    driver: bridge

